osx_image: xcode10.2
language: swift
xcode_project: XyCore.xcodeproj
xcode_scheme: XyCore
xcode_destination: platform=iOS Simulator,OS=11.0,name=iPhone X
addons:
  sonarcloud:
    organization: xyo-network
